db-config {
    port = 5432
    password = postgres
    username = postgres
    driver = "org.postgresql.Driver"
    host = "localhost"
    n-threads = 32
    ssl-mode-require = false
    migrations-table = "FlywaySchemaHistory"
    migrations-locations = [
        "classpath:db/migrations"
    ]
    name = "insider"
}

alchemy {
    api-key = "SLOaDzgDhqcslDh40g31a"
    ctf-address = "0xc5d563a36ae78145c45a50134d48a1215220f80a"
    burn-mint-address = "0xd91E80cF2E7be2e162c6513ceD06f1dD0dA35296"
}