db-config {
    port = 5432
    password = postgres
    username = postgres
    driver = "org.postgresql.Driver"
    host = "localhost"
    n-threads = 32
    ssl-mode-require = false
    migrations-table = "FlywaySchemaHistory"
    migrations-locations = [
        "classpath:db/migrations"
    ]
    name = "insider"
}

alchemy {
    api-key = "SLOaDzgDhqcslDh40g31a"
}