db-config {
    port = 5432
    password = postgres
    username = postgres
    driver = "org.postgresql.Driver"
    host = "localhost"
    n-threads = 32
    ssl-mode-require = false
    migrations-table = "FlywaySchemaHistory"
    migrations-locations = [
        "classpath:db/migrations"
    ]
    name = "insider"
}

alchemy {
    api-key = "oEJoUdc8ldfhEuzUNlTY7"
    ctf-address = "0xc5d563a36ae78145c45a50134d48a1215220f80a"
    burn-mint-address = "0xd91e80cf2e7be2e162c6513ced06f1dd0da35296"
    collateral-address = "0x3a3bd7bb9528e159577f7c2e685cc81a765002e2"
}