version: "3.9"
services:

  postgres:
    image: postgres
    container_name: insider_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insider
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql
    networks:
      - migration_net

  clickhouse:
    image: clickhouse/clickhouse-server:24.1
    container_name: clickhouse_insider
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./ch_config/config.xml:/etc/clickhouse-server/config.d/docker.xml
      - ./ch_config/users.xml:/etc/clickhouse-server/users.d/docker.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    networks:
      - migration_net

networks:
  migration_net:
    driver: bridge

volumes:
  clickhouse_data:
