version: "3.9"
services:
  postgres:
    image: postgres
    container_name: insider_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insider
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data